import db from '@lib/db'
import dayjs from 'dayjs'

type IParticulars = {
    qty: number,
    unit: string,
    description: string,
    stock_no: string,
    price: number
}

export const VIEW = async (id: string) => {
    const purchase_request = await db.purchase_requests.findFirst({
        include: {
            user: {
                select: {
                    id: true,
                    fname: true,
                    mname: true,
                    lname: true,
                    suffix: true,
                    department: {
                        select: {
                            description: true,
                            sections: {
                                select: {
                                    description: true
                                }
                            }
                        }
                    }
                }
            }
        },
        where: {
            id
        }
    })

    if (purchase_request !== null) {
        //compute total
        const particulars: IParticulars[] = (purchase_request.particulars as IParticulars[])
        const particularsWithTotal = particulars.map((item, idx) => {
            const total = item.price * item.qty;
            return { ...item, key: idx, total }
        })
        //
        const response = {
            ...purchase_request,
            user: `${purchase_request.user?.fname}${purchase_request.user?.mname ? " " + purchase_request.user.mname.substring(0, 1) + "." : ''} ${purchase_request.user?.lname}${purchase_request.user?.suffix ? " " + purchase_request.user?.suffix : ''}`,
            department: purchase_request.user?.department?.description,
            section: (purchase_request.user?.department?.sections as any).description || null,
            particulars: particularsWithTotal,
            date: dayjs(purchase_request.date).toISOString(),
            userId: purchase_request.userId
        }

        return response;
    } else {
        return null;
    }
}

type IClientPR = {
    // id autogenerated by prisma
    pr_no: string,
    date: string, //!note parse the `date` in client side since fetch() cannot send date objects in json
    particulars: IParticulars[],
    sai: string,
    obr: string,
    reference: string,
    budget: number,
    purpose: string
    userId: string,
}
//make sure that the clientside data is loaded -> NextRequest.json() 
export const CREATE = async (data: IClientPR) => {
    try {
        const parsed = {
            ...data,
            date: data.date, //!note parse date from clients since fetch does not support date objects
            tracking: [] //todo set default office get this from the user department or if admin
        }

        await db.purchase_requests.create({
            data: parsed
        })

        return true
    } catch (err) {
        return null
    }
}

export const UPDATE = async (data: IClientPR, prId: string) => {
    try {
        const parsed = {
            ...data,
        }

        await db.purchase_requests.update({
            data: { ...parsed },
            where: { id: prId }
        })

        return true
    } catch (err) {
        return null;
    }
}

export const SETFINAL = async (prId: string) => {
    try {
        await db.purchase_requests.update({
            data: { final: true },
            where: { id: prId }
        })
        return true
    } catch (err) {
        return null;
    }

}