export const UNIT_OF_MEASUREMENTS = [
    { value: 'bx', name: 'Box' },
    { value: 'ch', name: 'Container' },
    { value: 'cn', name: 'Can' },
    { value: 'cq', name: 'Cartrige' },
    { value: 'cs', name: 'Case' },
    { value: 'ct', name: 'Carton' },
    { value: 'cy', name: 'Cubic Yard' },
    { value: 'ea', name: 'Each' },
    { value: 'ft', name: 'Foot' },
    { value: 'hr', name: 'Hour' },
    { value: 'in', name: 'Inch' },
    { value: 'lf', name: 'Linear Foot' },
    { value: 'ln', name: 'Length' },
    { value: 'pc', name: 'Piece' },
    { value: 'pk', name: 'Pack' },
    { value: 'qt', name: 'Quart' },
    { value: 'sh', name: 'Sheet' },
    { value: 'tb', name: 'Tube' },
    { value: 'un', name: 'Unit' },
]